// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using today.Data;

#nullable disable

namespace today.Migrations.DbGroup
{
    [DbContext(typeof(DbGroupContext))]
    partial class DbGroupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("today.Entities.Group", b =>
                {
                    b.Property<int>("groupCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("groupCode"));

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("groupCode");

                    b.ToTable("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
