// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using today.Data;

#nullable disable

namespace today.Migrations.DbFactory
{
    [DbContext(typeof(DbFactoryContext))]
    partial class DbFactoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("today.Entities.Factory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("factoryCode")
                        .HasColumnType("int");

                    b.Property<string>("factoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("groupCode")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Factories");
                });
#pragma warning restore 612, 618
        }
    }
}
